In [ ]:
import csv
import subprocess
import pandas as pd
import requests
import git
import json
import os
from git import Repo
import os
import pandas as pd
import numpy as np

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.22.4)

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4)

In [ ]:
pip install git

ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git

In [ ]:
pip install json

ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json

In [ ]:
pip install csv

ERROR: Could not find a version that satisfies the requirement csv (from versions: none)
ERROR: No matching distribution found for csv

In [ ]:
pip install subprocess

ERROR: Could not find a version that satisfies the requirement subprocess (from versions: none)
ERROR: No matching distribution found for subprocess

In [ ]:
pip install os

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

In [ ]:
import os

In [ ]:
!pip install GitPython

Collecting GitPython
  Downloading GitPython-3.1.32-py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.5/188.5 kB 2.5 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1 (from GitPython)
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 4.7 MB/s eta 0:00:00
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython)
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Installing collected packages: smmap, gitdb, GitPython
Successfully installed GitPython-3.1.32 gitdb-4.0.10 smmap-5.0.0

In [ ]:
#Clone the Github Repository
os.system('git clone https://github.com/PhonePe/pulse.git')

NameError: ignored

# Aggregate Transaction

In [ ]:
root_dir = (r'/content/pulse/data')
# Loop over all the state folders
data_list = []

# Loop over all the state folders
for state_dir in os.listdir(os.path.join(root_dir, '/content/pulse/data/aggregated/transaction/country/india/state')):
    state_path = os.path.join(root_dir, '/content/pulse/data/aggregated/transaction/country/india/state', state_dir)
    if os.path.isdir(state_path):

        # Loop over all the year folders
        for year_dir in os.listdir(state_path):
            year_path = os.path.join(state_path, year_dir)
            if os.path.isdir(year_path):

                # Loop over all the JSON files (one for each quarter)
                for json_file in os.listdir(year_path):
                    if json_file.endswith('.json'):
                        with open(os.path.join(year_path, json_file)) as f:
                            data = json.load(f)

                            # Extract the data we're interested in
                            for transaction_data in data['data']['transactionData']:
                                row_dict = {
                                    'States': state_dir,
                                    'Transaction_Year': year_dir,
                                    'Quarters': int(json_file.split('.')[0]),
                                    'Transaction_Type': transaction_data['name'],
                                    'Transaction_Count': transaction_data['paymentInstruments'][0]['count'],
                                    'Transaction_Amount': transaction_data['paymentInstruments'][0]['amount']
                                }
                                data_list.append(row_dict)

# Convert list of dictionaries to dataframe
df1 = pd.DataFrame(data_list)
df1

,States,Transaction_Year,Quarters,Transaction_Type,Transaction_Count,Transaction_Amount
0,himachal-pradesh,2020,1,Recharge & bill payments,1815157,5.423568e+08
1,himachal-pradesh,2020,1,Peer-to-peer payments,1594806,6.431827e+09
2,himachal-pradesh,2020,1,Merchant payments,711018,4.274970e+08
3,himachal-pradesh,2020,1,Financial Services,4711,3.172304e+06
4,himachal-pradesh,2020,1,Others,18788,1.461376e+07
...,...,...,...,...,...,...
3589,odisha,2019,2,Peer-to-peer payments,16455353,4.142329e+10
3590,odisha,2019,2,Recharge & bill payments,7845252,1.506620e+09
3591,odisha,2019,2,Merchant payments,4827067,1.664621e+09
3592,odisha,2019,2,Financial Services,202705,2.042421e+07
3593,odisha,2019,2,Others,181647,1.398973e+08

# Aggregate User

In [ ]:
root_dir = '/content/pulse/data/aggregated/user/country/india/state'
df2_list = []

for state_dir in os.listdir(root_dir):
    state_path = os.path.join(root_dir, state_dir)
    if os.path.isdir(state_path):
        for json_file in os.listdir(state_path):
            if json_file.endswith('.json'):
                with open(os.path.join(state_path, json_file), 'r') as f:
                    json_data = json.load(f)
                    if isinstance(json_data, list):
                        df2_list += json_data
                    else:
                        df2_list.append(json_data)
        if df2_list:
            df2 = pd.json_normalize(df2_list)
            df2['subfolder'] = state_dir
            df2['subsubfolder'] = 'state'
df2 = pd.DataFrame(data_list)
df2

,States,Transaction_Year,Quarters,Transaction_Type,Transaction_Count,Transaction_Amount
0,himachal-pradesh,2020,1,Recharge & bill payments,1815157,5.423568e+08
1,himachal-pradesh,2020,1,Peer-to-peer payments,1594806,6.431827e+09
2,himachal-pradesh,2020,1,Merchant payments,711018,4.274970e+08
3,himachal-pradesh,2020,1,Financial Services,4711,3.172304e+06
4,himachal-pradesh,2020,1,Others,18788,1.461376e+07
...,...,...,...,...,...,...
3589,odisha,2019,2,Peer-to-peer payments,16455353,4.142329e+10
3590,odisha,2019,2,Recharge & bill payments,7845252,1.506620e+09
3591,odisha,2019,2,Merchant payments,4827067,1.664621e+09
3592,odisha,2019,2,Financial Services,202705,2.042421e+07
3593,odisha,2019,2,Others,181647,1.398973e+08

# Map Transaction

In [ ]:
root_dir = (r'/content/pulse/data')

# Initialize empty list to hold dictionaries of data for each JSON file
data_list = []

# Loop over all the state folders
for state_dir in os.listdir(os.path.join(root_dir, '/content/pulse/data/map/transaction/hover/country/india/state')):
    state_path = os.path.join(root_dir, '/content/pulse/data/map/transaction/hover/country/india/state', state_dir)
    if os.path.isdir(state_path):

        # Loop over all the year folders
        for year_dir in os.listdir(state_path):
            year_path = os.path.join(state_path, year_dir)
            if os.path.isdir(year_path):

                # Loop over all the JSON files (one for each quarter)
                for json_file in os.listdir(year_path):
                    if json_file.endswith('.json'):
                        with open(os.path.join(year_path, json_file)) as f:
                            data = json.load(f)

                            # Extract the data we're interested in
                            for hoverDataList in data['data']['hoverDataList']:
                                row_dict = {
                                    'States': state_dir,
                                    'Transaction_Year': year_dir,
                                    'Quarters': int(json_file.split('.')[0]),
                                    'District': hoverDataList['name'],
                                    'Transaction_Type': hoverDataList['metric'][0]['type'],
                                    'Transaction_Count': hoverDataList['metric'][0]['amount']
                                }
                                data_list.append(row_dict)

# Convert list of dictionaries to dataframe
df3 = pd.DataFrame(data_list)
df3

,States,Transaction_Year,Quarters,District,Transaction_Type,Transaction_Count
0,himachal-pradesh,2020,1,solan district,TOTAL,1.293084e+09
1,himachal-pradesh,2020,1,sirmaur district,TOTAL,3.869909e+08
2,himachal-pradesh,2020,1,shimla district,TOTAL,2.725599e+09
3,himachal-pradesh,2020,1,bilaspur district,TOTAL,2.269263e+08
4,himachal-pradesh,2020,1,hamirpur district,TOTAL,3.120506e+08
...,...,...,...,...,...,...
14631,odisha,2019,2,gajapati district,TOTAL,2.827619e+08
14632,odisha,2019,2,nayagarh district,TOTAL,5.913541e+08
14633,odisha,2019,2,nabarangpur district,TOTAL,2.700598e+08
14634,odisha,2019,2,kendrapara district,TOTAL,8.475452e+08
14635,odisha,2019,2,cuttack district,TOTAL,3.195750e+09

# Map user

In [ ]:
root_dir = '/content/pulse/data/map/user/hover/country/india/state'

# Initialize empty list to hold dictionaries of data for each JSON file
data_list = []

# Loop over all the state folders
for state_dir in os.listdir(root_dir):
    state_path = os.path.join(root_dir, state_dir)
    if os.path.isdir(state_path):

        # Loop over all the year folders
        for year_dir in os.listdir(state_path):
            year_path = os.path.join(state_path, year_dir)
            if os.path.isdir(year_path):

                # Loop over all the JSON files (one for each quarter)
                for json_file in os.listdir(year_path):
                    if json_file.endswith('.json'):
                        with open(os.path.join(year_path, json_file)) as f:
                            data = json.load(f)

                            # Extract the data we're interested in
                            for district, values in data['data']['hoverData'].items():
                                row_dict = {
                                    'States': state_dir,
                                    'Transaction_Year': year_dir,
                                    'Quarter': int(json_file.split('.')[0]),
                                    'District': district,
                                    'RegisteredUsers': values['registeredUsers'],
                                }
                                data_list.append(row_dict)

# Convert list of dictionaries to dataframe
df4 = pd.DataFrame(data_list)
df4

,States,Transaction_Year,Quarter,District,RegisteredUsers
0,himachal-pradesh,2020,1,solan district,220293
1,himachal-pradesh,2020,1,sirmaur district,77972
2,himachal-pradesh,2020,1,shimla district,139890
3,himachal-pradesh,2020,1,bilaspur district,54024
4,himachal-pradesh,2020,1,hamirpur district,73945
...,...,...,...,...,...
14635,odisha,2019,2,gajapati district,34063
14636,odisha,2019,2,nayagarh district,106745
14637,odisha,2019,2,nabarangpur district,37091
14638,odisha,2019,2,kendrapara district,144710
14639,odisha,2019,2,cuttack district,417809

# Top transaction

In [ ]:
root_dir = (r'/content/pulse/data')

# Initialize empty list to hold dictionaries of data for each JSON file
data_list = []

# Loop over all the state folders
for state_dir in os.listdir(os.path.join(root_dir, '/content/pulse/data/top/transaction/country/india/state')):
    state_path = os.path.join(root_dir, '/content/pulse/data/top/transaction/country/india/state', state_dir)
    if os.path.isdir(state_path):

        # Loop over all the year folders
        for year_dir in os.listdir(state_path):
            year_path = os.path.join(state_path, year_dir)
            if os.path.isdir(year_path):

                # Loop over all the JSON files (one for each quarter)
                for json_file in os.listdir(year_path):
                    if json_file.endswith('.json'):
                        with open(os.path.join(year_path, json_file)) as f:
                            data = json.load(f)

                            # Extract the data we're interested in
                            for districts in data['data']['districts']:
                                row_dict = {
                                    'States': state_dir,
                                    'Transaction_Year': year_dir,
                                    'Quarters': int(json_file.split('.')[0]),
                                    'District': districts['entityName'],
                                    'Transaction_Type': districts['metric']['type'],
                                    'Transaction_Count': districts['metric']['count'],
                                    'Transaction_Amount': districts['metric']['amount']
                                }
                                data_list.append(row_dict)

# Convert list of dictionaries to dataframe
df5 = pd.DataFrame(data_list)
df5

,States,Transaction_Year,Quarters,District,Transaction_Type,Transaction_Count,Transaction_Amount
0,himachal-pradesh,2020,1,shimla,TOTAL,1115491,2.725599e+09
1,himachal-pradesh,2020,1,solan,TOTAL,821088,1.293084e+09
2,himachal-pradesh,2020,1,kangra,TOTAL,569437,8.362832e+08
3,himachal-pradesh,2020,1,mandi,TOTAL,357222,5.820318e+08
4,himachal-pradesh,2020,1,hamirpur,TOTAL,247878,3.120506e+08
...,...,...,...,...,...,...,...
5915,odisha,2019,2,puri,TOTAL,808325,1.052201e+09
5916,odisha,2019,2,bhadrak,TOTAL,793895,1.136520e+09
5917,odisha,2019,2,kendujhar,TOTAL,778337,1.270399e+09
5918,odisha,2019,2,sundargarh,TOTAL,769791,1.356882e+09
5919,odisha,2019,2,anugul,TOTAL,656270,1.100527e+09

# Top user

In [ ]:
root_dir = '/content/pulse/data/top/user/country/india/state'

# Initialize empty list to hold dictionaries of data for each JSON file
data_list = []

# Loop over all the state folders
for state_dir in os.listdir(root_dir):
    state_path = os.path.join(root_dir, state_dir)
    if os.path.isdir(state_path):

        # Loop over all the year folders
        for year_dir in os.listdir(state_path):
            year_path = os.path.join(state_path, year_dir)
            if os.path.isdir(year_path):

                # Loop over all the JSON files
                for json_file in os.listdir(year_path):
                    if json_file.endswith('.json'):
                        with open(os.path.join(year_path, json_file)) as f:
                            data = json.load(f)

                            # Extract the data we're interested in
                            for district in data['data']['districts']:
                                row_dict = {
                                    'State': state_dir,
                                    'Transaction_Year': year_dir,
                                    'Quarters': int(json_file.split('.')[0]),
                                    'District': district['name'] if 'name' in district else district['pincode'],
                                    'RegisteredUsers': district['registeredUsers'],
                                }
                                data_list.append(row_dict)

# Convert list of dictionaries to dataframe
df6 = pd.DataFrame(data_list)
df6

                 State Transaction_Year  Quarters    District  RegisteredUsers
0     himachal-pradesh             2020         1       solan           220293
1     himachal-pradesh             2020         1      kangra           205367
2     himachal-pradesh             2020         1      shimla           139890
3     himachal-pradesh             2020         1       mandi           124971
4     himachal-pradesh             2020         1     sirmaur            77972
...                ...              ...       ...         ...              ...
5915            odisha             2019         2  sundargarh           226776
5916            odisha             2019         2        puri           217206
5917            odisha             2019         2   kendujhar           188657
5918            odisha             2019         2     bhadrak           187084
5919            odisha             2019         2      anugul           169261

[5920 rows x 5 columns]

# Cleaning

In [ ]:
# Drop any duplicates
d1 = df1.drop_duplicates()
d2 = df2.drop_duplicates()
d3 = df3.drop_duplicates()
d4 = df4.drop_duplicates()
d5 = df5.drop_duplicates()
d6 = df6.drop_duplicates()

In [ ]:
#checking Null values
null_counts = d1.isnull().sum()
print(null_counts)

States                0
Transaction_Year      0
Quarters              0
Transaction_Type      0
Transaction_Count     0
Transaction_Amount    0
dtype: int64

In [ ]:
null_counts = d2.isnull().sum()
print(null_counts)

States                0
Transaction_Year      0
Quarters              0
Transaction_Type      0
Transaction_Count     0
Transaction_Amount    0
dtype: int64

In [ ]:
null_counts = d3.isnull().sum()
print(null_counts)

States               0
Transaction_Year     0
Quarters             0
District             0
Transaction_Type     0
Transaction_Count    0
dtype: int64

In [ ]:
null_counts = d4.isnull().sum()
print(null_counts)

States              0
Transaction_Year    0
Quarter             0
District            0
RegisteredUsers     0
dtype: int64

In [ ]:
null_counts = d5.isnull().sum()
print(null_counts)

States                0
Transaction_Year      0
Quarters              0
District              0
Transaction_Type      0
Transaction_Count     0
Transaction_Amount    0
dtype: int64

In [ ]:
null_counts = d6.isnull().sum()
print(null_counts)

State               0
Transaction_Year    0
Quarters            0
District            0
RegisteredUsers     0
dtype: int64

In [ ]:
sa

In [ ]:
d1.to_csv('agg_trans.csv', index=False)
d2.to_csv('agg_user.csv', index=False)
d3.to_csv('map_tran.csv', index=False)
d4.to_csv('map_user.csv', index=False)
d5.to_csv('top_tran.csv', index=False)
d6.to_csv('top_user.csv', index=False)

In [ ]:
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')
Agg_trans = pd.read_csv(r'/content/agg_trans.csv')